feat: adds publishing service
Informasjonsforvaltning/dataset-catalog pull request #50
Opened 2020-12-14 13:11 UTC by matsjs

2020-12-17 09:04 UTC, azaxarov requested changes

2020-12-17 09:04 UTC, azaxarov commented on src/main/kotlin/no/fdk/dataset_catalog/service/PublishingService.kt
> +        if (publisherId != null) {
kan også bruke `publisherId?.let { ... } ?: logger.warn()`

2020-12-17 12:01 UTC, matsjs commented on src/main/kotlin/no/fdk/dataset_catalog/model/Catalog.kt
> +    val dataSourceType: String? = "DCAT-AP-NO",
For å utlede dette må man nødvendigvis iterere gjennom datasettene i katalogen, som da vil skje hver gang et datasett publiseres. Mer effektivt å bare toggle og lagre det i en boolean.

Enig når det kommer til dataSourceType, men var usikker på om datasett også skulle kunne lagres med SKOS type

2020-12-17 12:12 UTC, matsjs commented on src/main/resources/application.yml
> +  exchangeName: harvests
Det under rabbitmq properties setter opp RabbitTemplate, mens denne brukes til å sette opp en TopicExchange dersom den ikke allerede finens

2020-12-17 12:17 UTC, azaxarov commented on src/main/kotlin/no/fdk/dataset_catalog/model/Catalog.kt
> +    val dataSourceType: String? = "DCAT-AP-NO",
Med utlede tenkte jeg på en Spring data query som ligner på `countDatasetsByStatusInPublished` eller noe sånt, men ja boolean flag på catalog funker også

2020-12-17 13:41 UTC, azaxarov approved these changes

2020-12-18 07:25 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataset_catalog/model/Catalog.kt
> +    val hasPublishedDataset: Boolean? = false,
Hvis en katalog har 1 publisert datasett, som så avpubliseres, vil da denne settes tilbake til false?

Eller er kanskje hasPublishedDataset et noe misvisende navn?

2020-12-18 08:31 UTC, NilsOveTen approved these changes

2020-12-18 08:35 UTC, merged