Fix/mjs/non nullable fields
Informasjonsforvaltning/dataset-catalog pull request #56
Opened 2021-01-18 13:45 UTC by matsjs

2021-01-18 13:51 UTC, stigbd approved these changes

2021-01-18 13:53 UTC, NilsOveTen requested changes

2021-01-18 13:53 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
> +        registrationStatus = updateValue(newValues.registrationStatus, registrationStatus, toUpdate.contains("registrationStatus")),
Hva er det updateValue gjør som ikke dekkes av `newValues.blabla ?: blabla`?

2021-01-18 14:05 UTC, azaxarov requested changes

2021-01-18 14:05 UTC, azaxarov commented on src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
> +        val patch: Dataset = mapper.readValue(patchString)
Forstår ikke helt gevinsten bak denne endringen

2021-01-18 14:21 UTC, NilsOveTen commented
Ok, så litt nærmere på dette. Er stor motstander av å gjøre det på denne måten...

2021-01-18 17:11 UTC, NilsOveTen requested changes

2021-01-18 17:11 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
> +            startDate = LocalDate.parse(it.startDate),
```
startDate = updateTime(it.startDate, dboTime?.startDate),
endDate = updateTime(it.endDate, dboTime?.endDate))
```

2021-01-18 17:11 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
> +fun Dataset.update(newValues: DatasetDTO): Dataset =
Siden du uansett hadde behov for `.toDBO()` så trenger du egentlig ikke gjøre endringer her, bare map til dbo før `.update()`. Men same-same, gjør det du føler er mest leselig.

2021-01-19 08:35 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
> +            startDate = updateTime(dto.startDate, dboTime?.getOrNull(index)?.startDate),
Krever ikke dette at dtoTime og dboTime har akkurat samme sortering?

2021-01-19 09:12 UTC, NilsOveTen approved these changes

2021-01-19 09:26 UTC, azaxarov approved these changes

2021-01-19 09:26 UTC, azaxarov commented on src/test/kotlin/no/fdk/dataset_catalog/service/DatasetServiceTest.kt
> +val mapper = jacksonObjectMapper()
ikke lenger nødvendig

2021-01-19 09:26 UTC, azaxarov commented on src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
> +        modified = updateTime(newValues.modified,modified),
formattering

2021-01-19 10:35 UTC, merged